#!/usr/bin/env sh

swaykill() {
	swaymsg '[all] kill' && sleep "${1:-0.3}"
}

case "$(bemenu -p 'Power' -cl 7 -W 0.2 <<__EOF__
1. Lock
2. Reload
3. Exit
4. Suspend
5. Hibernate
6. Reboot
7. Power Off
__EOF__
)" in
	*"Lock") loginctl lock-session ;;
	*"Reload") swaymsg reload ;;
	*"Suspend") swaykill 1 && systemctl suspend-then-hibernate ;;
	*"Hibernate") swaykill 1 && systemctl hibernate ;;
	*"Exit") swaykill && swaymsg exit ;;
	*"Reboot") swaykill && systemctl reboot ;;
	*"Power Off") swaykill && systemctl poweroff ;;
	*) exit 1 ;;
esac
