#!/usr/bin/env zsh


setopt -xuo pipefail -o err_return
unset pid

json() {
	 jq -rc "$@"
}

logw() {
	echo "[LOG] $@" || :
	jq -rc || :
}

loop() {
	local event_json cid tree_json parent tree_json parent
	read -rspt 5 event_json
	logw event <<<$event_json
	[[ $(json '.change' <<<$event_json) == 'focus' ]]
	[[ $(json '.container.type' <<<$event_json) != 'floating_con' ]]
	json '.container.id' <<<$event_json | read -rs cid

	swaymsg -rt get_tree | json | read -rs tree_json
	logw tree <<<$tree_json

	json "..|objects|select(.nodes|arrays|any(.id == ${cid}))" \
		<<<$tree_json | read -rs parent
	logw parent <<<$parent
	[[ $(json '.layout' <<<$parent) != 'tabbed' ]]

	swaymsg "[con_id=${cid}] split t, layout tabbed" | json | read -rs out
	logw output <<<$out
}

coproc swaymsg -mrt subscribe '["window"]'
pid=$!

while ps -p $pid >/dev/null; do loop || :; done
