#!/usr/bin/env sh

swaykill() {
	swaymsg '[all] kill' && sleep 1
}

case "$(bemenu -p 'Power' -cl 8 -W 0.2 <<__EOF__
1. Lock
2. Reload
3. Exit
4. Log Off
5. Suspend
6. Hibernate
7. Reboot
8. Power Off
__EOF__
)" in
	*"Lock") loginctl lock-session ;;
	*"Reload") swaymsg reload ;;
	*"Suspend") sleep 1 && systemctl suspend-then-hibernate ;;
	*"Hibernate") sleep 1 && systemctl hibernate ;;
	*"Exit") swaykill && swaymsg exit ;;
	*"Log Off") swaykill && systemctl --user exit && swaymsg exit ;;
	*"Reboot") swaykill && systemctl reboot ;;
	*"Power Off") swaykill && systemctl poweroff ;;
	*) exit 1 ;;
esac
