#!/usr/bin/env zsh


setopt -xuo pipefail -o err_return
unset pid

pprint() {
	 jq -rc || :
}

loop() {
	local event_json
	read -rspt 5 event_json
	pprint <<<$event_json
	[[ $(jq -rc '.change' <<<$event_json) == 'focus' ]]
	[[ $(jq -rc '.container.type' <<<$event_json) != 'floating_con' ]]
	local cid=$(jq -rc '.container.id' <<<$event_json)

	local tree_json=$(swaymsg -rt get_tree)
	pprint <<<$tree_json

	local parent=$(jq -rc \
		"..|objects|select(.nodes|arrays|any(.id == ${cid}))" \
		<<<$tree_json)
	pprint <<<$parent
	[[ $(jq -rc '.layout' <<<$parent) != 'tabbed' ]]

	out=$(swaymsg "[con_id=${cid}] split t, layout tabbed")
	pprint <<<$out
}

coproc swaymsg -mrt subscribe '["window"]'
pid=$!

while ps -p $pid >/dev/null; do loop || :; done
