alias -g \
	C='| tee >(wl-copy) | bat -pp' \
	G='| rg' \
	P="|& $PAGER" \
	B='&>/dev/null &!' \

alias \
	df='duf' \
	diff='delta' \
	du='dust' \
	ps='procs' \
	cp='cp -ir' \
	ln='ln -si' \
	mv='mv -i' \
	radeontop='sudo radeontop -cT' \
	rm='rmtrash -I' \
	rmdir='rmdirtrash -p' \
	rmrm='rm -iv' \
	rmrmdir='rmdir -pv' \
	cc='gcc -Wall -Wextra -Wpedantic' \
	cxx='g++ -Wall -Wextra -Wpedantic' \
	hs='ghc -Weverything' \
	l='eza -lbg --git --hyperlink' \
	lS='eza -labgs size --color-scale --group-directories-first --hyperlink' \
	la='eza -labg --git --hyperlink' \
	ldot='eza -labgd --git --hyperlink .*' \
	lr='eza -lbgT --hyperlink' \
	lR='eza -labgT --hyperlink' \
	ls='eza --hyperlink' \
	'..'='cd ..' \
	c='cal -3' \
	copy='wl-copy' \
	drag='dragon-drop' \
	fetch='fastfetch' \
	ffupload='ffsend upload -vd 20 -e 7d' \
	h='history 1' \
	idr='rlwrap -n idris2' \
	idrc='idris2 --total' \
	ipy='ipython' \
	matrix='cmatrix -ab' \
	md='mkdir -p' \
	open='xdg-open' \
	paste='wl-paste' \
	pip='python -m pip' \
	py='python' \
	sc='systemctl' \
	scu='systemctl --user' \
	sl='sl -ae -50' \
	ssc='sudo systemctl' \
	su='sudo -i' \
	svi='sudoedit' \
	swapflush='sudo swapoff -va; sudo swapon -va' \
	tmuxattachall='while tmux attach-session; do done' \
	updb='sudo updatedb' \
	v='bat' \
	vi="$EDITOR" \
	vidiff='nvim -d' \
	xsh='exec zsh' \
	xssh='exec ssh' \
	xsu='exec sudo -i' \
	xtm='exec tmux' \
	yt='yt-dlp' \
	za='zathura' \
	venv='source .venv/bin/activate' \
	unvenv='deactivate' \
	g='git' \
	ga='git add' \
	gaa='git add --all' \
	gau='git add --update' \
	gb='git branch' \
	gba='git branch --all' \
	gc='git commit' \
	gcl='git clone' \
	gcn='git clean -diX' \
	gd='git diff' \
	gdd='git diff --cached' \
	gdt='git difftool' \
	gddt='git difftool --cached' \
	gf='git fetch --all' \
	gg='git log' \
	ggg='git log --oneline --graph' \
	gid='git rev-parse HEAD' \
	gl='git merge --ff-only @{u}' \
	gld='git diff HEAD..@{u}' \
	glg='git log HEAD..@{u}' \
	glsf='for repo in */; do (cd "$repo" && test -e .git && git fetch --all) & done; wait' \
	gp='git push' \
	gpd='git diff @{u}..HEAD' \
	gpf='git push --force-with-lease' \
	gr='git remote -v' \
	grm='git restore --staged' \
	gst='git stash push -u' \
	gsta='git stash apply --index' \
	gstl='git stash list' \
	gstp='git stash pop --index' \
	gstw='git stash show --patch -u' \
	gsw='git switch' \
	gt='git status' \
	gw='git show' \
